# Generated by Django 3.1.6 on 2021-02-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Family', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Zip_Code', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=10)),
                ('Phone_Whats_App', models.CharField(max_length=10)),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('Size_Of_Product', models.CharField(max_length=10)),
                ('Description', models.TextField()),
                ('Debt_Rate', models.FloatField()),
                ('Type_Of_Product', models.CharField(max_length=10)),
            ],
        ),
    ]
