# Generated by Django 3.1.6 on 2021-03-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Tipax_Code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customers',
            name='Type_Of_Send',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
