# Generated by Django 3.1.6 on 2021-03-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210228_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Type_Of_Send',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
