# Generated by Django 3.1.6 on 2021-02-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCustomers', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Family', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=10)),
                ('Pic', models.ImageField(upload_to='')),
                ('SizeOfProduct', models.CharField(max_length=10)),
            ],
        ),
    ]
