# Generated by Django 3.1.6 on 2021-02-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
